apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibha-automation
  namespace: default
  labels:
    app: bibha-automation
    version: "1.112.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bibha-automation
  template:
    metadata:
      labels:
        app: bibha-automation
    spec:
      containers:
      - name: bibha-automation
        image: bibhaadmin8888/bibha-automation:1.112.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5678
          name: http
        env:
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "https"
        - name: N8N_HOST
          value: "automation.bibhadigital.com"  # Update with your domain
        - name: WEBHOOK_URL
          value: "https://automation.bibhadigital.com"  # Update with your domain
        - name: N8N_DIAGNOSTICS_ENABLED
          value: "false"
        - name: N8N_PERSONALIZATION_ENABLED
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: bibha-automation-pvc
      nodeSelector:
        kubernetes.io/arch: arm64  # Ensure deployment on ARM64 nodes
---
apiVersion: v1
kind: Service
metadata:
  name: bibha-automation-service
  namespace: default
spec:
  type: LoadBalancer  # Or ClusterIP if using Ingress
  selector:
    app: bibha-automation
  ports:
  - port: 80
    targetPort: 5678
    protocol: TCP
    name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bibha-automation-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2  # Update based on your EKS storage class